exp_tank_colmap:
  Config: config_tank.yaml
  Module: colmap
  NumRuns: 1
  Parameters:
    matcher_type: exhaustive
    mode: mono
    use_gpu: 1
    verbose: 0
    step_size: 10

# exp_tank_glomap:
#   Config: config_tank.yaml
#   Module: glomap
#   NumRuns: 1
#   Parameters:
#     matcher_type: exhaustive
#     mode: mono
#     use_gpu: 1
#     verbose: 0
