exp_debug_colmap:
  Config: config_debug.yaml
  Module: colmap
  NumRuns: 1
  Parameters:
    matcher_type: exhaustive
    matching_type: aliked_lightglue
    mapper_type: glomap
    mode: mono
    use_gpu: 1
    verbose: 0
    step_size: 2
