feb_miss_slg_col:
  Config: config_liz_miss.yaml
  Module: colmap
  NumRuns: 1
  Parameters:
    matcher_type: exhaustive
    matching_type: sift_lightglue
    mapper_type: colmap
    mode: mono
    use_gpu: 1
    verbose: 0
    step_size: 1

