mal_slg_raw:
  Config: config_mal_raw.yaml
  Module: colmap
  NumRuns: 1
  Parameters:
    matcher_type: exhaustive
    matching_type: sift_lightglue
    mapper_type: colmap
    mode: mono
    use_gpu: 1
    verbose: 0
    step_size: 3

